#!/usr/bin/env perl

use strict;
use warnings;

use Graph::Easy::Weighted;

my $attr = 'probability';
my $gw = Graph::Easy::Weighted->new();
$gw->populate(
    {
        W => { X => 0.4, Z => 0.6 }, # Vertex W with 2 edges, weight 1
        X => { W => 0.3, Y => 0.7 }, # Vertex X "    2 "
        Y => { W => 0.5, Y => 0.5 }, # Vertex Y "    2 "
        Z => { W => 0.2, X => 0.8 }, # Vertex Z "    2 "
    },
    $attr
);

for my $vertex ( $gw->vertices ) {
    printf "vertex: %s weight=%.2f\n",
        $vertex->name, $gw->get_cost($vertex, $attr);
    for my $edge ( $gw->edges ) {
        next if $edge->from->name ne $vertex->name;
        printf "\tedge to: %s weight=%.2f\n",
            $edge->to->name, $gw->get_cost($edge, $attr);
    }
}

print $gw->as_ascii();
